### ISSUE TITLE
inference/pipeline/entry.py FAILED

### ISSUE THREAD

**Issue by IAMJOYBO** [SandAI-org/MAGI-1#61]
```bash
root@64780383f350:/MAGI-1# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
root@64780383f350:/MAGI-1#
```

```python
[W507 17:47:53.414335406 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[rank0]: Traceback (most recent call last):
[rank0]:   File "/MAGI-1/inference/pipeline/entry.py", line 54, in <module>
[rank0]:     main()
[rank0]:   File "/MAGI-1/inference/pipeline/entry.py", line 37, in main
[rank0]:     pipeline = MagiPipeline(args.config_file)
[rank0]:   File "/MAGI-1/inference/pipeline/pipeline.py", line 31, in __init__
[rank0]:     dist_init(self.config)
[rank0]:   File "/MAGI-1/inference/infra/distributed/dist_utils.py", line 48, in dist_init
[rank0]:     assert config.engine_config.cp_size * config.engine_config.pp_size == torch.distributed.get_world_size()
[rank0]: AssertionError
[rank0]:[W507 17:47:54.111377586 ProcessGroupNCCL.cpp:1187] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0507 17:47:55.065000 139705155674752 torch/distributed/elastic/multiprocessing/api.py:832] failed (exitcode: 1) local_rank: 0 (pid: 8009) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0a0+3bcc3cddb5.nv24.7', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 900, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 891, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
inference/pipeline/entry.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-07_17:47:55
  host      : 64780383f350
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8009)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by levi131** [comment]
Thank you very much for your attention to our work. I carefully analyzed the script and error message you provided, but I failed to reproduce the problem on the H800 machine. I suspect that this problem is related to the H20 machine you are using and I will continue to try to reproduce the problem. You can also try to run Magi-1 on other GPUs like H800 or 4090.

**Comment by levi131** [comment]
@IAMJOYBO  Could you run `lscpu | grep avx512` on your H20 and show me the result?

**Comment by levi131** [comment]
I run Magi-1 on H20 and it works fine. I found a related issue https://github.com/NVIDIA/TensorRT-LLM/issues/1717, and the conclusion is that upgrading the cuda driver and toolkit version can solve the zero division problem on H20 machines. You can try it.
